apiVersion: v1
kind: Pod
metadata:
  name: application-pod
  labels:
    app: application
spec:
  containers:
  - name: application-container
    image: 359775151382.dkr.ecr.us-east-1.amazonaws.com/colorapp-awsecr:latest
    ports:
    - containerPort: 8080
