apiVersion: v1
kind: Pod
metadata:
  name: colorapp-pod
  labels:
    app: colorapp
spec:
  containers:
  - name: colorapp
    image: 359775151382.dkr.ecr.us-east-1.amazonaws.com/colorapp-awsecr:latest
    ports:
    - containerPort: 8080
