apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: colorapp-replicaset
  labels:
    app: colorapp

spec:
  replicas: 3
  selector:
    matchLabels:
      app: colorapp

  template:
    metadata:
      labels:
        app: colorapp
    spec:
      containers:
        - name: colorapp
          image: 359775151382.dkr.ecr.us-east-1.amazonaws.com/colorapp-awsecr:latest
          env:
          - name: DBHOST
            value: "mysql.sankar-db.svc.cluster.local"
          - name: DBUSER
            value: "root"
          - name: DBPWD
            value: "pw"
          - name: DBPORT
            value: "3306"
          - name: APP_COLOR
            value: "lime"
          - name: DATABASE
            value: "employees"
          ports:
              - containerPort: 8080