apiVersion: v1
kind: Service
metadata:
  name: colorapp
  labels:
    app: colorapp
spec:

  selector:
      app: colorapp

  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000