apiVersion: apps/v1
kind: Deployment
metadata:
  name: colorapp-deployment
  labels:
    app: colorapp

spec:
  replicas: 3
  selector:
    matchLabels:
      app: colorapp

  template:
    metadata:
      labels:
        app: colorapp

    spec:
      containers:
        - name: colorapp
          image: 359775151382.dkr.ecr.us-east-1.amazonaws.com/colorapp-awsecr:latest
          imagePullPolicy: Always
          env:
            - name: DBHOST
              value: "mysql.sankarnath-db.svc.cluster.local"
            - name: DBUSER
              value: "root"
            - name: DBPWD
              value: "pw"
            - name: DBPORT
              value: "3306"
          ports:
              - containerPort: 8080