apiVersion: v1
kind: Pod
metadata:
  name: mysqldb-pod
  labels:
    app: mysqldb
spec:
  containers:
    - name: mysqldb
      image: 359775151382.dkr.ecr.us-east-1.amazonaws.com/mysqldb-awsecr:latest
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
      
